version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=db
      - MARIADB_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql

